### ISSUE TITLE
Octopus' mouth doesn't appear on pre-Oreo devices

### ISSUE THREAD

**Issue by ZeevoX** [ZeevoX/Ocquarium#1]
Here is how the octopus _should_ look (screenshot taken from an Oreo device)

![screenshot of ocquarium on oreo](https://lh3.googleusercontent.com/KZ3R1-omVm3WNQ0fDhye-kIoFxQ_FdOOumZTcxAJYyRXpgO-5JV7GCPoUdJF5bCVQceH=h500-rw)
Notice that the octopus has a line for its mouth.

Here is a screenshot from a Marshmallow device

![screenshot of ocquarium on marshmallow](https://lh3.googleusercontent.com/zO98VOwTe7ARmRGfG2t8jV7Sk7qaempLclziXxm4Emfek-_uEl9gwdAD9yn1XHopfzA=h500-rw)

The octopus doesn't have a mouth.

I believe that [this](https://github.com/ZeevoX/Ocquarium/blob/master/app/src/main/java/com/zeevox/octo/bhs/OctopusDrawable.java#L248) is the source of the problem.

This issue has been reported by multiple users on [Google](https://play.google.com/store/apps/details?id=com.zeevox.octo&reviewId=Z3A6QU9xcFRPRXdUcF9pVk9UbHIwYVczYXBzYmZoNVVscFY3Tkl4VEhtRGtBMEVwUUNoR1pfdEpEODJXZzFVVTB4WE1sUkxzOENaQ2JUZ2RVQ05KZ0tnTXc) [Play.](https://play.google.com/store/apps/details?id=com.zeevox.octo&reviewId=Z3A6QU9xcFRPR2dRTzcyV050aVJlTVF2UkxNbEZaQWo5ekVMNEFJVE03OU5PZFFFNjB2cWtBYUtsdmptNkZtME9VMERIWWpCWkhRVVktWmd6QVVYa0ZUUUE)

**Comment by WAVDEVTEAM** [comment]
Edit canvas.drawOutRect(point.x - 61f, point.y + 8f, point.x + 61f, point.y + 12f) with canvas.clipRect(point.x - 61f, point.y + 8f, point.x + 61f, point.y + 12f,Region.Op.DIFFERENCE);

**Comment by ZeevoX** [comment]
@WAVDEVTEAM Thank you for your suggestion, I'll make sure to have a look.
