### ISSUE TITLE
Improved Code Formatting + Shell Legacy Syntax Removed

### ISSUE THREAD

**Issue by harens** [ZeevoX/Ocquarium#47]
The PR does not necessarily fix any existing issues, but instead works on improving syntax.

To achieve this, [Align-YAML](https://github.com/jonschlinkert/align-yaml), [Beautysh](https://github.com/bemeurer/beautysh), [Uncrustify](https://github.com/uncrustify/uncrustify), and [ShellCheck](https://github.com/koalaman/shellcheck) have been used.
The [octoStyle.cfg](https://github.com/harens/Ocquarium/blob/master/octoStyle.cfg) file is used to configure Uncrustify, and is based on [ben.cfg.txt](https://github.com/uncrustify/uncrustify/blob/master/documentation/htdocs/ben.cfg.txt).

[Dependabot](https://dependabot.com/) updated dependencies, and [ImgBot](https://imgbot.net/) optimised images.

**Comment by harens** [comment]
The PR is https://github.com/ZeevoX/Ocquarium/pull/48

**Comment by ZeevoX** [comment]
Thank you for the pull request - may I close this issue?

**Comment by harens** [comment]
That's fine
