### ISSUE TITLE
Travis CI not publishing APKs to Telegram

### ISSUE THREAD

**Issue by ZeevoX** [ZeevoX/Ocquarium#51]
https://travis-ci.org/ZeevoX/Ocquarium/builds/441000110#L1572

```
find: unknown predicate `-1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (43) A libcurl function was given a bad argument
```

**Comment by ZeevoX** [comment]
Probably related to #50 - any insight, @harens?

**Comment by harens** [comment]
In terms of the scripts, all that was changed were the shebangs (to fix ShellCheck Error [SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039)), as well as changing [`ls` to `find`](https://github.com/ZeevoX/Ocquarium/blob/master/scripts/deploy-telegram.sh#L20) (to fix ShellCheck Error [SC2012](https://github.com/koalaman/shellcheck/wiki/SC2012))

However, it is probably related to #50, and so I'll try and help to find the problem

**Comment by ZeevoX** [comment]
Looks like it's the `-1` on [line 20](https://github.com/ZeevoX/Ocquarium/blob/master/scripts/deploy-telegram.sh).

**Comment by harens** [comment]
Appears that the easiest way to solve this is to undo this change. Though it goes against the ShellCheck warning, this can be put as an exception
