### ISSUE TITLE
Limit input for Octopus size preference

### ISSUE THREAD

**Issue by ZeevoX** [ZeevoX/Ocquarium#8]
I have been receiving many error stacktraces on Google Play with NumberFormatException's due to the fact that people are entering invalid input into the Octopus size preferences in settings.

The main issues in this case are:
1. People enter a decimal value.
2. People enter a string instead of an int (**one** instead of **1**)
3. People enter a larger minimum value than maximum and vice-versa.

The input should be limited to purely whole integers.

This would probably require changing the EditTextPreference into a custom SeekBarPreference.

**Comment by WAVDEVTEAM** [comment]
No you can change the input type with type number
